# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

#[[social]]
#identifier = "Discord"
#name = "Discord"
#url = "https://github.com/Rmingz"

#[social.params]
#icon = "brand-discord"


